fruit1 = input("Enter 1: ")
fruit2 = input("Enter 2: ")
fruit3 = input("Enter 3: ")
fruit4 = input("Enter 4: ")
fruit5 = input("Enter 5: ")
fruit6 = input("Enter 6: ")
fruit7 = input("Enter 7: ")
print(fruit1, fruit2, fruit3, fruit4, fruit5, fruit6, fruit7)